### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "user7@gmail.com",
    "password": "user7"
}

### Signin an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "user5@gmail.com",
    "password": "user5"
}

### Signout
POST http://localhost:3000/auth/signout

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with given ID
GET http://localhost:3000/auth/1

### Find all users with given email
GET http://localhost:3000/auth?email=user@gmail.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/3 
Content-Type: application/json

{
    "email": "user.demo@gmail.com",
    "password": "user.demo"
}